name: Publish

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/publish
      with:
        username: ${{ secrets.OSSRH_USERNAME }}
        password: ${{ secrets.OSSRH_PASSWORD }}
        key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        pat: ${{ secrets.PAT }}
        repos: ${{ vars.TARGET_REPOS }}
        event: ${{ vars.EVENT_TYPE }}
